---
# tasks file for roles/xyz_tomcat
  - name: Downloading required Tomcat from url
    get_url:
      url: "{{ req_tomcat_var }}"
      dest: /usr/local

  - name: Extrating downloaded tomcat
    unarchive:
      src: "/usr/local/{{tomcat_ver}}"
      dest: /usr/local
      remote_src: yes
  - name: Renaming tomcat home
    command: mv "{{tomcat_path_old}}" "{{tomcat_path}}"

  - name: Replacing default port with required port
    template:
      src: templates/server.xml.j2
      dest: /usr/local/latest/conf/server.xml

    notify: Starting_tomcat




