#!/usr/bin/ansible-playbook
---
  - name: working with Jinja2 template playbooks
    hosts: all
    gather_facts: no
    become: yes
    vars:
      httpd_port: 8000  
    tasks:
      - name: Coping a file to manged nodes
        template:
          src: jinja-example.j2
          dest: /usr/src/done_with_jinja-example-file.txt
