---
  - name: installing httpd on CentOS servers
    become: yes
    yum:
      name: httpd
      state: latest
    register: httpd_pkg
  - debug:
        msg:
                - "{{ httpd_pkg.results }}"
  - name: starting and enabling httpd server
    become: yes
    service:
      name: httpd
      state: started
      enabled: yes


