#!/usr/bin/ansible-playbook
---
 - name: simple play to install httpd server
   hosts: all 
   gather_facts: yes
   tasks:
     - import_tasks: install_webserver_CentOS.yml
       when: ansible_distribution == "CentOS"
     
     - import_tasks: install_webserver_Ubuntu.yml
       when: ansible_distribution == "Ubuntu"


     - import_tasks: install_java_CentOS.yml
       when: ansible_distribution == "CentOS"

     - import_tasks: install_java_Ubuntu.yml
       when: ansible_distribution == "Ubuntu"
