#!/usr/bin/ansible-playbook
---
 - hosts: localhost
   name: Play for AIRTHMETIC Operations
   gather_facts: no

   vars:
     x: 56
     y: 33
   
   tasks:
   - name: displaying values
     debug:
       msg:
       - "The value of x: {{x}}"
       - "the valus of y: {{y}}"
       - "{{x}} + {{y}} = {{x+y}}"
       - "{{x}} - {{y}} = {{x-y}}"
       - "{{y}} - {{y}} = {{y-x}}"
       - "{{x}} * {{y}} = {{y*x}}"
