#!/usr/bin/ansible-playbook
---
 - hosts: localhost
   name: working on IF CONDITION or when conditional statement
   gather_facts: no

   vars:
     x: 5
     y: 67
     my_list: [5,6,7]

   tasks:
   - debug:
       msg:
       - "the value os x {{x}} and y value is {{y}}"
     when: 
     - x == y

   - debug:
       msg:
       - "x is present in my_list"
     when: 
     #-  x in my_list
     -  x in my_list
