#!/usr/bin/ansible-playbook
---
 - hosts: localhost
   name: error handling ....success output 1 and failed than output code non-zero
   gather_facts: no
   tasks:
      - command: "ls /home"
        register: home_out
      - debug:
            msg:
               - "{{ home_out.stdout }}"

      - command: "ls -l /etc/ssh/ssh_config-ashish"
        register: centrifydc_connected
        ignore_errors: yes
      - debug:
            msg:
               - "{{ centrifydc_connected }}"
