#!/usr/bin/ansible-playbook
---
 - name: DEFNING VARS AND CALLING IN TASKS
   hosts: all
   become: no
   gather_facts: yes


   tasks:
   #- debug: 
       #var: ansible_facts   
   #- debug: 
   #    var: ansible_facts.os_family
   - debug:
       msg:
       - "The OS Distro is : {{ansible_distribution}}"
       - "The os name is : {{ansible_system}}"
       - "The OS Family is : {{ansible_os_family}}"
