#!/usr/bin/ansible-playbook
---
 - name: simple play to install httpd server
   hosts: all 
   gather_facts: yes
   tasks:
     - name: installing httpd on CentOS servers
       become: yes
       yum: 
         name: httpd
         state: latest
       when: ansible_distribution == "CentOS"
     
     - name: installing apache2 on Ubuntu servers
       become: yes
       apt: 
         name: apache2
         state: latest
       when: ansible_distribution == "Ubuntu"


     - name: starting and enabling httpd server
       become: yes
       service:
         name: httpd
         state: started
         enabled: yes
       when:  ansible_distribution == "CentOS" 

     - name: starting and enabling apache2 service 
       become: yes
       service:
         name: apache2
         state: started
         enabled: yes
       when: ansible_distribution == "Ubuntu"
