#!/usr/bin/ansible-playbook
---
 - hosts: localhost
   name: Member ship operatior examples
   gather_facts: no
   
   vars:
     x: [3,4,5,6]
     y: 5

   tasks:
   - debug:
       msg:
       - "The list sequence of x: {{x}}, and value of y: {{y}}"
       - "y is in x: {{ y in x}}"
       - "y is in x: {{ 10 in x}}"
       - "y is not in x: {{ y not in x}}"
       - "y is not in x: {{ y not in x}}"
